/*
 * $Id$
 */

package com.calix.bseries.server.dbmodel;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/
//BEGIN IMPORTS
import java.util.ArrayList;
import java.util.Collection;

import java.util.Iterator;

import com.calix.ems.database.C7Database;
import com.calix.ems.database.DbTransaction;
import com.calix.ems.exception.EMSDatabaseException;
import com.calix.ems.exception.EMSException;
import com.calix.ems.query.EMSGetAllQuery;
import com.calix.ems.query.ICMSQuery;
import com.calix.system.common.log.Log;
//END IMPORTS
//---------------------------------/

import com.calix.ems.util.TLVHelper;
import com.calix.system.common.protocol.tlv.TLV;
import com.calix.system.server.dbmodel.*;
import com.calix.system.server.dbmodel.ICMSAid;

/**
 * Class B6PSDProfile.
 * 
 * @version $Revision$ $Date$
 */
public class B6PSDProfile extends com.calix.system.server.dbmodel.CMSObject {


      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field m_DPBOE_Min_UsableSignal
     */
    public String m_DPBOE_Min_UsableSignal;

    /**
     * Field m_DPBOE_Side_Cable_ModelAnnex_A
     */
    public String m_DPBOE_Side_Cable_ModelAnnex_A;

    /**
     * Field m_DPBOE_Side_Cable_ModelAnnex_B
     */
    public String m_DPBOE_Side_Cable_ModelAnnex_B;

    /**
     * Field m_DPBOE_Side_Cable_ModelAnnex_C
     */
    public String m_DPBOE_Side_Cable_ModelAnnex_C;

    /**
     * Field m_DPBOE_Side_ElectricalLength
     */
    public String m_DPBOE_Side_ElectricalLength;

    /**
     * Field m_DPBO_US1_A
     */
    public String m_DPBO_US1_A;

    /**
     * Field m_DPBO_US1_B
     */
    public String m_DPBO_US1_B;

    /**
     * Field m_DPBO_US1_K10
     */
    public String m_DPBO_US1_K10;

    /**
     * Field m_DPBO_US2_A
     */
    public String m_DPBO_US2_A;

    /**
     * Field m_DPBO_US2_B
     */
    public String m_DPBO_US2_B;

    /**
     * Field m_DPBO_US2_K10
     */
    public String m_DPBO_US2_K10;

    /**
     * Field m_ELECtricalLength
     */
    public String m_ELECtricalLength;

    /**
     * Field m_binderId
     */
    public Integer m_binderId;

    /**
     * Field m_description
     */
    public String m_description;

    /**
     * Field m_dpboE_EndingTone
     */
    public Integer m_dpboE_EndingTone;

    /**
     * Field m_dpboE_StartingTone
     */
    public Integer m_dpboE_StartingTone;

    /**
     * Field m_dpboState
     */
    public Integer m_dpboState;

    /**
     * Field m_id
     */
    public com.calix.system.server.dbmodel.ICMSAid m_id;

    /**
     * Field m_isAutogenerated
     */
    public Integer m_isAutogenerated;

    /**
     * Field m_name
     */
    public String m_name;

    /**
     * Field m_psdMask
     */
    public Integer m_psdMask;

    /**
     * Field m_rfiBands
     */
    public String m_rfiBands;

    /**
     * Field m_rfiGaps
     */
    public String m_rfiGaps;

    /**
     * Field m_servicePackage_PSD
     */
    public String m_servicePackage_PSD;

    /**
     * Field TYPE_NAME
     */
    public static String TYPE_NAME = "B6PSDProfile";

    /**
     * Field flowID
     */
    public static final int flowID = 1;


      //----------------/
     //- Constructors -/
    //----------------/

    public B6PSDProfile() {
        super();
    } //-- com.calix.bseries.server.dbmodel.B6PSDProfile()


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method copyFields
     * 
     * @param obj1
     */
    protected void copyFields(CMSObject obj1)
    {
        if( obj1 instanceof B6PSDProfile ) {
            super.copyFields(obj1);
            B6PSDProfile obj = (B6PSDProfile)obj1;
            setDPBOE_Min_UsableSignal((String)Helper.copy(obj.getDPBOE_Min_UsableSignal()));
            setDPBOE_Side_Cable_ModelAnnex_A((String)Helper.copy(obj.getDPBOE_Side_Cable_ModelAnnex_A()));
            setDPBOE_Side_Cable_ModelAnnex_B((String)Helper.copy(obj.getDPBOE_Side_Cable_ModelAnnex_B()));
            setDPBOE_Side_Cable_ModelAnnex_C((String)Helper.copy(obj.getDPBOE_Side_Cable_ModelAnnex_C()));
            setDPBOE_Side_ElectricalLength((String)Helper.copy(obj.getDPBOE_Side_ElectricalLength()));
            setDPBO_US1_A((String)Helper.copy(obj.getDPBO_US1_A()));
            setDPBO_US1_B((String)Helper.copy(obj.getDPBO_US1_B()));
            setDPBO_US1_K10((String)Helper.copy(obj.getDPBO_US1_K10()));
            setDPBO_US2_A((String)Helper.copy(obj.getDPBO_US2_A()));
            setDPBO_US2_B((String)Helper.copy(obj.getDPBO_US2_B()));
            setDPBO_US2_K10((String)Helper.copy(obj.getDPBO_US2_K10()));
            setELECtricalLength((String)Helper.copy(obj.getELECtricalLength()));
            setbinderId((Integer)Helper.copy(obj.getbinderId()));
            setdescription((String)Helper.copy(obj.getdescription()));
            setdpboE_EndingTone((Integer)Helper.copy(obj.getdpboE_EndingTone()));
            setdpboE_StartingTone((Integer)Helper.copy(obj.getdpboE_StartingTone()));
            setdpboState((Integer)Helper.copy(obj.getdpboState()));
            setid((com.calix.system.server.dbmodel.ICMSAid)Helper.copy(obj.getid()));
            setisAutogenerated((Integer)Helper.copy(obj.getisAutogenerated()));
            setname((String)Helper.copy(obj.getname()));
            setpsdMask((Integer)Helper.copy(obj.getpsdMask()));
            setrfiBands((String)Helper.copy(obj.getrfiBands()));
            setrfiGaps((String)Helper.copy(obj.getrfiGaps()));
            setservicePackage_PSD((String)Helper.copy(obj.getservicePackage_PSD()));
            setIdentityValue((com.calix.system.server.dbmodel.ICMSAid)Helper.copy(obj.getIdentityValue()));
        }
    } //-- void copyFields(CMSObject) 

    /**
     * Method getDPBOE_Min_UsableSignal
     */
    public String getDPBOE_Min_UsableSignal()
    {
        return this.m_DPBOE_Min_UsableSignal;
    } //-- String getDPBOE_Min_UsableSignal() 

    /**
     * Method getDPBOE_Side_Cable_ModelAnnex_A
     */
    public String getDPBOE_Side_Cable_ModelAnnex_A()
    {
        return this.m_DPBOE_Side_Cable_ModelAnnex_A;
    } //-- String getDPBOE_Side_Cable_ModelAnnex_A() 

    /**
     * Method getDPBOE_Side_Cable_ModelAnnex_B
     */
    public String getDPBOE_Side_Cable_ModelAnnex_B()
    {
        return this.m_DPBOE_Side_Cable_ModelAnnex_B;
    } //-- String getDPBOE_Side_Cable_ModelAnnex_B() 

    /**
     * Method getDPBOE_Side_Cable_ModelAnnex_C
     */
    public String getDPBOE_Side_Cable_ModelAnnex_C()
    {
        return this.m_DPBOE_Side_Cable_ModelAnnex_C;
    } //-- String getDPBOE_Side_Cable_ModelAnnex_C() 

    /**
     * Method getDPBOE_Side_ElectricalLength
     */
    public String getDPBOE_Side_ElectricalLength()
    {
        return this.m_DPBOE_Side_ElectricalLength;
    } //-- String getDPBOE_Side_ElectricalLength() 

    /**
     * Method getDPBO_US1_A
     */
    public String getDPBO_US1_A()
    {
        return this.m_DPBO_US1_A;
    } //-- String getDPBO_US1_A() 

    /**
     * Method getDPBO_US1_B
     */
    public String getDPBO_US1_B()
    {
        return this.m_DPBO_US1_B;
    } //-- String getDPBO_US1_B() 

    /**
     * Method getDPBO_US1_K10
     */
    public String getDPBO_US1_K10()
    {
        return this.m_DPBO_US1_K10;
    } //-- String getDPBO_US1_K10() 

    /**
     * Method getDPBO_US2_A
     */
    public String getDPBO_US2_A()
    {
        return this.m_DPBO_US2_A;
    } //-- String getDPBO_US2_A() 

    /**
     * Method getDPBO_US2_B
     */
    public String getDPBO_US2_B()
    {
        return this.m_DPBO_US2_B;
    } //-- String getDPBO_US2_B() 

    /**
     * Method getDPBO_US2_K10
     */
    public String getDPBO_US2_K10()
    {
        return this.m_DPBO_US2_K10;
    } //-- String getDPBO_US2_K10() 

    /**
     * Method getELECtricalLength
     */
    public String getELECtricalLength()
    {
        return this.m_ELECtricalLength;
    } //-- String getELECtricalLength() 

    /**
     * Method getIdentityValue
     */
    public com.calix.system.server.dbmodel.ICMSAid getIdentityValue()
    {
        return this.m_id;
    } //-- com.calix.system.server.dbmodel.ICMSAid getIdentityValue() 

    /**
     * Method getTlvType
     */
    public int getTlvType()
    {
        return BseriesTlvConstants.B6PSDProfile;
    } //-- int getTlvType() 

    /**
     * Method getTypeName
     */
    public String getTypeName()
    {
        return TYPE_NAME;
    } //-- String getTypeName() 

    /**
     * Method getbinderId
     */
    public Integer getbinderId()
    {
        return this.m_binderId;
    } //-- Integer getbinderId() 

    /**
     * Method getdescription
     */
    public String getdescription()
    {
        return this.m_description;
    } //-- String getdescription() 

    /**
     * Method getdpboE_EndingTone
     */
    public Integer getdpboE_EndingTone()
    {
        return this.m_dpboE_EndingTone;
    } //-- Integer getdpboE_EndingTone() 

    /**
     * Method getdpboE_StartingTone
     */
    public Integer getdpboE_StartingTone()
    {
        return this.m_dpboE_StartingTone;
    } //-- Integer getdpboE_StartingTone() 

    /**
     * Method getdpboState
     */
    public Integer getdpboState()
    {
        return this.m_dpboState;
    } //-- Integer getdpboState() 

    /**
     * Method getid
     */
    public com.calix.system.server.dbmodel.ICMSAid getid()
    {
        return this.m_id;
    } //-- com.calix.system.server.dbmodel.ICMSAid getid() 

    /**
     * Method getisAutogenerated
     */
    public Integer getisAutogenerated()
    {
        return this.m_isAutogenerated;
    } //-- Integer getisAutogenerated() 

    /**
     * Method getname
     */
    public String getname()
    {
        return this.m_name;
    } //-- String getname() 

    /**
     * Method getpsdMask
     */
    public Integer getpsdMask()
    {
        return this.m_psdMask;
    } //-- Integer getpsdMask() 

    /**
     * Method getrfiBands
     */
    public String getrfiBands()
    {
        return this.m_rfiBands;
    } //-- String getrfiBands() 

    /**
     * Method getrfiGaps
     */
    public String getrfiGaps()
    {
        return this.m_rfiGaps;
    } //-- String getrfiGaps() 

    /**
     * Method getservicePackage_PSD
     */
    public String getservicePackage_PSD()
    {
        return this.m_servicePackage_PSD;
    } //-- String getservicePackage_PSD() 

    /**
     * Method populateAttributeFromTLV
     * 
     * @param tlv
     * @param from_version
     */
    public void populateAttributeFromTLV(TLV tlv, SwVersionNo from_version)
    {
        if (tlv == null)
            return;
        switch (tlv.getType()) {
            case 0x346A:
                if (m_name == null) {
                    m_name = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x346B:
                if (m_description == null) {
                    m_description = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x346C:
                if (m_isAutogenerated == null) {
                    m_isAutogenerated = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x346D:
                if (m_binderId == null) {
                    m_binderId = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x346E:
                if (m_dpboE_StartingTone == null) {
                    m_dpboE_StartingTone = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x346F:
                if (m_dpboE_EndingTone == null) {
                    m_dpboE_EndingTone = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3470:
                if (m_DPBO_US2_K10 == null) {
                    m_DPBO_US2_K10 = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3471:
                if (m_DPBOE_Side_ElectricalLength == null) {
                    m_DPBOE_Side_ElectricalLength = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3472:
                if (m_DPBOE_Side_Cable_ModelAnnex_C == null) {
                    m_DPBOE_Side_Cable_ModelAnnex_C = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3473:
                if (m_DPBOE_Side_Cable_ModelAnnex_B == null) {
                    m_DPBOE_Side_Cable_ModelAnnex_B = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3474:
                if (m_DPBO_US1_K10 == null) {
                    m_DPBO_US1_K10 = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3475:
                if (m_DPBOE_Side_Cable_ModelAnnex_A == null) {
                    m_DPBOE_Side_Cable_ModelAnnex_A = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3476:
                if (m_DPBO_US2_B == null) {
                    m_DPBO_US2_B = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3477:
                if (m_DPBO_US2_A == null) {
                    m_DPBO_US2_A = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3478:
                if (m_DPBOE_Min_UsableSignal == null) {
                    m_DPBOE_Min_UsableSignal = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3479:
                if (m_ELECtricalLength == null) {
                    m_ELECtricalLength = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x347A:
                if (m_rfiBands == null) {
                    m_rfiBands = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x347B:
                if (m_servicePackage_PSD == null) {
                    m_servicePackage_PSD = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x347C:
                if (m_DPBO_US1_B == null) {
                    m_DPBO_US1_B = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x347D:
                if (m_DPBO_US1_A == null) {
                    m_DPBO_US1_A = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x347E:
                if (m_psdMask == null) {
                    m_psdMask = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x347F:
                if (m_dpboState == null) {
                    m_dpboState = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3480:
                if (m_rfiGaps == null) {
                    m_rfiGaps = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
        }
        super.populateAttributeFromTLV(tlv, from_version);
    } //-- void populateAttributeFromTLV(TLV, SwVersionNo) 

    /**
     * Method populateTLVFromAttributes
     * 
     * @param tlv
     * @param to_version
     */
    public void populateTLVFromAttributes(TLV tlv, SwVersionNo to_version)
    {
        if (tlv == null)
            return;
        super.populateTLVFromAttributes(tlv, to_version);
        TLVHelper.addEmbeddedTLV(tlv, 0x3478, m_DPBOE_Min_UsableSignal);
        TLVHelper.addEmbeddedTLV(tlv, 0x3475, m_DPBOE_Side_Cable_ModelAnnex_A);
        TLVHelper.addEmbeddedTLV(tlv, 0x3473, m_DPBOE_Side_Cable_ModelAnnex_B);
        TLVHelper.addEmbeddedTLV(tlv, 0x3472, m_DPBOE_Side_Cable_ModelAnnex_C);
        TLVHelper.addEmbeddedTLV(tlv, 0x3471, m_DPBOE_Side_ElectricalLength);
        TLVHelper.addEmbeddedTLV(tlv, 0x347D, m_DPBO_US1_A);
        TLVHelper.addEmbeddedTLV(tlv, 0x347C, m_DPBO_US1_B);
        TLVHelper.addEmbeddedTLV(tlv, 0x3474, m_DPBO_US1_K10);
        TLVHelper.addEmbeddedTLV(tlv, 0x3477, m_DPBO_US2_A);
        TLVHelper.addEmbeddedTLV(tlv, 0x3476, m_DPBO_US2_B);
        TLVHelper.addEmbeddedTLV(tlv, 0x3470, m_DPBO_US2_K10);
        TLVHelper.addEmbeddedTLV(tlv, 0x3479, m_ELECtricalLength);
        TLVHelper.addEmbeddedTLV(tlv, 0x346D, m_binderId);
        TLVHelper.addEmbeddedTLV(tlv, 0x346B, m_description);
        TLVHelper.addEmbeddedTLV(tlv, 0x346F, m_dpboE_EndingTone);
        TLVHelper.addEmbeddedTLV(tlv, 0x346E, m_dpboE_StartingTone);
        TLVHelper.addEmbeddedTLV(tlv, 0x347F, m_dpboState);
        TLVHelper.addEmbeddedTLV(tlv, 0x346C, m_isAutogenerated);
        TLVHelper.addEmbeddedTLV(tlv, 0x346A, m_name);
        TLVHelper.addEmbeddedTLV(tlv, 0x347E, m_psdMask);
        TLVHelper.addEmbeddedTLV(tlv, 0x347A, m_rfiBands);
        TLVHelper.addEmbeddedTLV(tlv, 0x3480, m_rfiGaps);
        TLVHelper.addEmbeddedTLV(tlv, 0x347B, m_servicePackage_PSD);
    } //-- void populateTLVFromAttributes(TLV, SwVersionNo) 

    /**
     * Method setDPBOE_Min_UsableSignal
     * 
     * @param DPBOE_Min_UsableSignal
     */
    public void setDPBOE_Min_UsableSignal(String DPBOE_Min_UsableSignal)
    {
        this.m_DPBOE_Min_UsableSignal = DPBOE_Min_UsableSignal;
    } //-- void setDPBOE_Min_UsableSignal(String) 

    /**
     * Method setDPBOE_Side_Cable_ModelAnnex_A
     * 
     * @param DPBOE_Side_Cable_ModelAnnex_A
     */
    public void setDPBOE_Side_Cable_ModelAnnex_A(String DPBOE_Side_Cable_ModelAnnex_A)
    {
        this.m_DPBOE_Side_Cable_ModelAnnex_A = DPBOE_Side_Cable_ModelAnnex_A;
    } //-- void setDPBOE_Side_Cable_ModelAnnex_A(String) 

    /**
     * Method setDPBOE_Side_Cable_ModelAnnex_B
     * 
     * @param DPBOE_Side_Cable_ModelAnnex_B
     */
    public void setDPBOE_Side_Cable_ModelAnnex_B(String DPBOE_Side_Cable_ModelAnnex_B)
    {
        this.m_DPBOE_Side_Cable_ModelAnnex_B = DPBOE_Side_Cable_ModelAnnex_B;
    } //-- void setDPBOE_Side_Cable_ModelAnnex_B(String) 

    /**
     * Method setDPBOE_Side_Cable_ModelAnnex_C
     * 
     * @param DPBOE_Side_Cable_ModelAnnex_C
     */
    public void setDPBOE_Side_Cable_ModelAnnex_C(String DPBOE_Side_Cable_ModelAnnex_C)
    {
        this.m_DPBOE_Side_Cable_ModelAnnex_C = DPBOE_Side_Cable_ModelAnnex_C;
    } //-- void setDPBOE_Side_Cable_ModelAnnex_C(String) 

    /**
     * Method setDPBOE_Side_ElectricalLength
     * 
     * @param DPBOE_Side_ElectricalLength
     */
    public void setDPBOE_Side_ElectricalLength(String DPBOE_Side_ElectricalLength)
    {
        this.m_DPBOE_Side_ElectricalLength = DPBOE_Side_ElectricalLength;
    } //-- void setDPBOE_Side_ElectricalLength(String) 

    /**
     * Method setDPBO_US1_A
     * 
     * @param DPBO_US1_A
     */
    public void setDPBO_US1_A(String DPBO_US1_A)
    {
        this.m_DPBO_US1_A = DPBO_US1_A;
    } //-- void setDPBO_US1_A(String) 

    /**
     * Method setDPBO_US1_B
     * 
     * @param DPBO_US1_B
     */
    public void setDPBO_US1_B(String DPBO_US1_B)
    {
        this.m_DPBO_US1_B = DPBO_US1_B;
    } //-- void setDPBO_US1_B(String) 

    /**
     * Method setDPBO_US1_K10
     * 
     * @param DPBO_US1_K10
     */
    public void setDPBO_US1_K10(String DPBO_US1_K10)
    {
        this.m_DPBO_US1_K10 = DPBO_US1_K10;
    } //-- void setDPBO_US1_K10(String) 

    /**
     * Method setDPBO_US2_A
     * 
     * @param DPBO_US2_A
     */
    public void setDPBO_US2_A(String DPBO_US2_A)
    {
        this.m_DPBO_US2_A = DPBO_US2_A;
    } //-- void setDPBO_US2_A(String) 

    /**
     * Method setDPBO_US2_B
     * 
     * @param DPBO_US2_B
     */
    public void setDPBO_US2_B(String DPBO_US2_B)
    {
        this.m_DPBO_US2_B = DPBO_US2_B;
    } //-- void setDPBO_US2_B(String) 

    /**
     * Method setDPBO_US2_K10
     * 
     * @param DPBO_US2_K10
     */
    public void setDPBO_US2_K10(String DPBO_US2_K10)
    {
        this.m_DPBO_US2_K10 = DPBO_US2_K10;
    } //-- void setDPBO_US2_K10(String) 

    /**
     * Method setELECtricalLength
     * 
     * @param ELECtricalLength
     */
    public void setELECtricalLength(String ELECtricalLength)
    {
        this.m_ELECtricalLength = ELECtricalLength;
    } //-- void setELECtricalLength(String) 

    /**
     * Method setIdentityValue
     * 
     * @param id
     */
    public boolean setIdentityValue(com.calix.system.server.dbmodel.ICMSAid id)
    {
        this.m_id = (com.calix.system.server.dbmodel.ICMSAid)id;
        return true;
    } //-- boolean setIdentityValue(com.calix.system.server.dbmodel.ICMSAid) 

    /**
     * Method setTypeName
     * 
     * @param typeName
     */
    public boolean setTypeName(String typeName)
    {
        return false;
    } //-- boolean setTypeName(String) 

    /**
     * Method setbinderId
     * 
     * @param binderId
     */
    public void setbinderId(Integer binderId)
    {
        this.m_binderId = binderId;
    } //-- void setbinderId(Integer) 

    /**
     * Method setdescription
     * 
     * @param description
     */
    public void setdescription(String description)
    {
        this.m_description = description;
    } //-- void setdescription(String) 

    /**
     * Method setdpboE_EndingTone
     * 
     * @param dpboE_EndingTone
     */
    public void setdpboE_EndingTone(Integer dpboE_EndingTone)
    {
        this.m_dpboE_EndingTone = dpboE_EndingTone;
    } //-- void setdpboE_EndingTone(Integer) 

    /**
     * Method setdpboE_StartingTone
     * 
     * @param dpboE_StartingTone
     */
    public void setdpboE_StartingTone(Integer dpboE_StartingTone)
    {
        this.m_dpboE_StartingTone = dpboE_StartingTone;
    } //-- void setdpboE_StartingTone(Integer) 

    /**
     * Method setdpboState
     * 
     * @param dpboState
     */
    public void setdpboState(Integer dpboState)
    {
        this.m_dpboState = dpboState;
    } //-- void setdpboState(Integer) 

    /**
     * Method setid
     * 
     * @param id
     */
    public void setid(com.calix.system.server.dbmodel.ICMSAid id)
    {
        this.m_id = id;
    } //-- void setid(com.calix.system.server.dbmodel.ICMSAid) 

    /**
     * Method setisAutogenerated
     * 
     * @param isAutogenerated
     */
    public void setisAutogenerated(Integer isAutogenerated)
    {
        this.m_isAutogenerated = isAutogenerated;
    } //-- void setisAutogenerated(Integer) 

    /**
     * Method setname
     * 
     * @param name
     */
    public void setname(String name)
    {
        this.m_name = name;
    } //-- void setname(String) 

    /**
     * Method setpsdMask
     * 
     * @param psdMask
     */
    public void setpsdMask(Integer psdMask)
    {
        this.m_psdMask = psdMask;
    } //-- void setpsdMask(Integer) 

    /**
     * Method setrfiBands
     * 
     * @param rfiBands
     */
    public void setrfiBands(String rfiBands)
    {
        this.m_rfiBands = rfiBands;
    } //-- void setrfiBands(String) 

    /**
     * Method setrfiGaps
     * 
     * @param rfiGaps
     */
    public void setrfiGaps(String rfiGaps)
    {
        this.m_rfiGaps = rfiGaps;
    } //-- void setrfiGaps(String) 

    /**
     * Method setservicePackage_PSD
     * 
     * @param servicePackage_PSD
     */
    public void setservicePackage_PSD(String servicePackage_PSD)
    {
        this.m_servicePackage_PSD = servicePackage_PSD;
    } //-- void setservicePackage_PSD(String) 

    /**
     * Method updateFields
     * 
     * @param obj1
     */
    protected void updateFields(CMSObject obj1)
    {
        if( obj1 instanceof B6PSDProfile ) {
            super.updateFields(obj1);
            B6PSDProfile obj = (B6PSDProfile)obj1;
           if (obj.getDPBOE_Min_UsableSignal() != null )
               setDPBOE_Min_UsableSignal((String)Helper.copy(obj.getDPBOE_Min_UsableSignal()));
           if (obj.getDPBOE_Side_Cable_ModelAnnex_A() != null )
               setDPBOE_Side_Cable_ModelAnnex_A((String)Helper.copy(obj.getDPBOE_Side_Cable_ModelAnnex_A()));
           if (obj.getDPBOE_Side_Cable_ModelAnnex_B() != null )
               setDPBOE_Side_Cable_ModelAnnex_B((String)Helper.copy(obj.getDPBOE_Side_Cable_ModelAnnex_B()));
           if (obj.getDPBOE_Side_Cable_ModelAnnex_C() != null )
               setDPBOE_Side_Cable_ModelAnnex_C((String)Helper.copy(obj.getDPBOE_Side_Cable_ModelAnnex_C()));
           if (obj.getDPBOE_Side_ElectricalLength() != null )
               setDPBOE_Side_ElectricalLength((String)Helper.copy(obj.getDPBOE_Side_ElectricalLength()));
           if (obj.getDPBO_US1_A() != null )
               setDPBO_US1_A((String)Helper.copy(obj.getDPBO_US1_A()));
           if (obj.getDPBO_US1_B() != null )
               setDPBO_US1_B((String)Helper.copy(obj.getDPBO_US1_B()));
           if (obj.getDPBO_US1_K10() != null )
               setDPBO_US1_K10((String)Helper.copy(obj.getDPBO_US1_K10()));
           if (obj.getDPBO_US2_A() != null )
               setDPBO_US2_A((String)Helper.copy(obj.getDPBO_US2_A()));
           if (obj.getDPBO_US2_B() != null )
               setDPBO_US2_B((String)Helper.copy(obj.getDPBO_US2_B()));
           if (obj.getDPBO_US2_K10() != null )
               setDPBO_US2_K10((String)Helper.copy(obj.getDPBO_US2_K10()));
           if (obj.getELECtricalLength() != null )
               setELECtricalLength((String)Helper.copy(obj.getELECtricalLength()));
           if (obj.getbinderId() != null )
               setbinderId((Integer)Helper.copy(obj.getbinderId()));
           if (obj.getdescription() != null )
               setdescription((String)Helper.copy(obj.getdescription()));
           if (obj.getdpboE_EndingTone() != null )
               setdpboE_EndingTone((Integer)Helper.copy(obj.getdpboE_EndingTone()));
           if (obj.getdpboE_StartingTone() != null )
               setdpboE_StartingTone((Integer)Helper.copy(obj.getdpboE_StartingTone()));
           if (obj.getdpboState() != null )
               setdpboState((Integer)Helper.copy(obj.getdpboState()));
           if (obj.getid() != null )
               setid((com.calix.system.server.dbmodel.ICMSAid)Helper.copy(obj.getid()));
           if (obj.getisAutogenerated() != null )
               setisAutogenerated((Integer)Helper.copy(obj.getisAutogenerated()));
           if (obj.getname() != null )
               setname((String)Helper.copy(obj.getname()));
           if (obj.getpsdMask() != null )
               setpsdMask((Integer)Helper.copy(obj.getpsdMask()));
           if (obj.getrfiBands() != null )
               setrfiBands((String)Helper.copy(obj.getrfiBands()));
           if (obj.getrfiGaps() != null )
               setrfiGaps((String)Helper.copy(obj.getrfiGaps()));
           if (obj.getservicePackage_PSD() != null )
               setservicePackage_PSD((String)Helper.copy(obj.getservicePackage_PSD()));
           if (obj.getIdentityValue() != null )
               setIdentityValue((com.calix.system.server.dbmodel.ICMSAid)Helper.copy(obj.getIdentityValue()));
        }
    } //-- void updateFields(CMSObject) 
//BEGIN CODE
 
   public void setdpbo_US2_K10(Double dpbo_US2_K10)
   {
	   if(dpbo_US2_K10 != null)
		   this.m_DPBO_US2_K10 = String.valueOf(dpbo_US2_K10);
	   else
		   this.m_DPBO_US2_K10 = null;
   }
   public void setdpboE_Side_ElectricalLength(Double dpboE_Side_ElectricalLength)
   {	
	   if(dpboE_Side_ElectricalLength != null)
	   		this.m_DPBOE_Side_ElectricalLength = String.valueOf(dpboE_Side_ElectricalLength);
	   else
		   	this.m_DPBOE_Side_ElectricalLength = null;
   }
   public void setdpboE_Side_Cable_ModelAnnex_C(Double dpboE_Side_Cable_ModelAnnex_C)
   {
	   if(dpboE_Side_Cable_ModelAnnex_C != null)
	   		this.m_DPBOE_Side_Cable_ModelAnnex_C = String.valueOf(dpboE_Side_Cable_ModelAnnex_C);
	   else
		   	this.m_DPBOE_Side_Cable_ModelAnnex_C = null;
   }
   public void setdpboE_Side_Cable_ModelAnnex_B(Double dpboE_Side_Cable_ModelAnnex_B)
   {
	   if(dpboE_Side_Cable_ModelAnnex_B != null)
	   		this.m_DPBOE_Side_Cable_ModelAnnex_B = String.valueOf(dpboE_Side_Cable_ModelAnnex_B);
	   else
		   	this.m_DPBOE_Side_Cable_ModelAnnex_B = null;
   }
   public void setdpbo_US1_K10(Double dpbo_US1_K10)
   {
	   if(dpbo_US1_K10 != null)
	   		this.m_DPBO_US1_K10 = String.valueOf(dpbo_US1_K10);
	   else
		   	this.m_DPBO_US1_K10 = null;
   }
   public void setdpboE_Side_Cable_ModelAnnex_A(Double dpboE_Side_Cable_ModelAnnex_A)
   {
	   if(dpboE_Side_Cable_ModelAnnex_A != null)
	   		this.m_DPBOE_Side_Cable_ModelAnnex_A = String.valueOf(dpboE_Side_Cable_ModelAnnex_A);
	   else
		   	this.m_DPBOE_Side_Cable_ModelAnnex_A = null;
   }
   public void setdpbo_US2_B(Double dpbo_US2_B)
   {
	   if(dpbo_US2_B != null)
	   		this.m_DPBO_US2_B = String.valueOf(dpbo_US2_B);
	   else
		   	this.m_DPBO_US2_B = null;
   }
   public void setdpbo_US2_A(Double dpbo_US2_A)
   {
	   if(dpbo_US2_A != null)
	   		this.m_DPBO_US2_A = String.valueOf(dpbo_US2_A);
	   else
		   	this.m_DPBO_US2_A = null;
   }
   public void setdpboE_Min_UsableSignal(Double dpboE_Min_UsableSignal)
   {
	   if(dpboE_Min_UsableSignal != null)
	   		this.m_DPBOE_Min_UsableSignal = String.valueOf(dpboE_Min_UsableSignal);
	   else
		   	this.m_DPBOE_Min_UsableSignal = null;
   }
   public void setelectricalLength(Double electricalLength)
   {
	   if(electricalLength != null)
	   		this.m_ELECtricalLength = String.valueOf(electricalLength);
	   else
		   	this.m_ELECtricalLength = null;
   }
   public void setdpbo_US1_B(Double dpbo_US1_B)
   {
	  if(dpbo_US1_B != null)
	   		this.m_DPBO_US1_B = String.valueOf(dpbo_US1_B);
	  else
		  	this.m_DPBO_US1_B = null;
   }
   public void setdpbo_US1_A(Double dpbo_US1_A)
   {
	   if(dpbo_US1_A != null)
	   		this.m_DPBO_US1_A = String.valueOf(dpbo_US1_A);
	   else
		   	this.m_DPBO_US1_A = null;
   }
   
   public Double getdpbo_US2_K10()
   {
	   if(this.m_DPBO_US2_K10 != null)
		   return Double.valueOf(this.m_DPBO_US2_K10).doubleValue();
	   else
		   return null;
   }
   public Double getdpboE_Side_ElectricalLength()
   {
	   if(this.m_DPBOE_Side_ElectricalLength != null)
		   return Double.valueOf(this.m_DPBOE_Side_ElectricalLength).doubleValue();
	   else
		   return null;
   }
   public Double getdpboE_Side_Cable_ModelAnnex_C()
   {
	   if(this.m_DPBOE_Side_Cable_ModelAnnex_C != null)
		   return Double.valueOf(this.m_DPBOE_Side_Cable_ModelAnnex_C).doubleValue();
	   else
		   return null;
   }
   public Double getdpboE_Side_Cable_ModelAnnex_B()
   {
	   if(this.m_DPBOE_Side_Cable_ModelAnnex_B != null)
		   return Double.valueOf(this.m_DPBOE_Side_Cable_ModelAnnex_B).doubleValue();
	   else
		   return null;
   }
   public Double getdpbo_US1_K10()
   {
	   if(this.m_DPBO_US1_K10 != null)
		   return Double.valueOf(this.m_DPBO_US1_K10).doubleValue();
	   else
		   return null;
   }
   public Double getdpboE_Side_Cable_ModelAnnex_A()
   {
	   if(this.m_DPBOE_Side_Cable_ModelAnnex_A != null)
		   return Double.valueOf(this.m_DPBOE_Side_Cable_ModelAnnex_A).doubleValue();
	   else
		   return null;
   }
   public Double getdpbo_US2_B()
   {
	   if(this.m_DPBO_US2_B != null)
		   return Double.valueOf(this.m_DPBO_US2_B).doubleValue();
	   else
		   return null;
   }
   public Double getdpbo_US2_A()
   {
	   if(this.m_DPBO_US2_A != null)
		   return Double.valueOf(this.m_DPBO_US2_A).doubleValue();
	   else
		   return null;
   }
   public Double getelectricalLength()
   {
	   if(this.m_ELECtricalLength != null)
		   return Double.valueOf(this.m_ELECtricalLength).doubleValue();
	   else
		   return null;
   }
   public Double getdpboE_Min_UsableSignal()
   {
	   if(this.m_DPBOE_Min_UsableSignal != null)
		   return Double.valueOf(this.m_DPBOE_Min_UsableSignal).doubleValue();
	   else
		   return null;
   }
   public Double getdpbo_US1_B()
   {
	   if(this.m_DPBO_US1_B != null)
		   return Double.valueOf(this.m_DPBO_US1_B).doubleValue();
	   else
		   return null;
   }
   public Double getdpbo_US1_A()
   {
	   if(this.m_DPBO_US1_A != null)
		   return Double.valueOf(this.m_DPBO_US1_A).doubleValue();
	   else
		   return null;
   }
 
    
public void setconvertId(Integer id) {
		this.m_id = new BSeriesAid(String.valueOf(id));
	} // -- void setconvertName(String)

	public Integer getconvertId() {
		return Integer.valueOf(this.m_id.toString());
	}

	public Collection doQuery(DbTransaction tx, String filter)
			throws EMSException {
		if (Log.db().isDebugEnabled())
			Log.db().debug("Inside doQuery");
		ICMSQuery query = getDBQuery(this.getTypeName(), null);
		Collection coll = query.exec((Object) tx.getDatabase(), (Object) tx);
		if (Log.db().isDebugEnabled())
			Log.db().debug("Out of doQuery");
		return coll;
	}
    public CMSObject doLoad(DbTransaction tx) throws EMSException {
    	C7Database db =C7Database.getInstance(); 
    	CMSObject obj = null;
    	try{
    	db.beginTransaction();
    	Collection resultList = db.executeQuery(this.getClass(), "id = "+this.getIdentityValue().toString(), -1, -1);
    	if(resultList != null&&!resultList.isEmpty()){
    			Iterator itr = resultList.iterator();
    			obj = (CMSObject)itr.next();
    	}
    	}catch(Exception e){
    		e.printStackTrace();
    		db.close();
    	}
    	finally{
    		db.close();
    	}
    	if(obj == null)
    		throw new EMSDatabaseException(EMSDatabaseException._loadNonExistentFail_, "Object does not exist");
    	else
    		return obj;
    }

	public ICMSQuery getDBQuery(String type, String filter) {
		if (filter == null || filter.equals(""))
			return new EMSGetAllQuery(type);
		else {
			Log.meta().error("BaseEMSObject: filterQuery is not supported");
			return null;
		}
	}

	public boolean isIdentityValuePrimaryKey() {
		return true;
	}
	
//END CODE
}