/*
 * $Id$
 */

package com.calix.bseries.server.dbmodel;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/
//BEGIN IMPORTS
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import com.calix.ems.database.C7Database;
import com.calix.ems.database.DbTransaction;
import com.calix.ems.exception.EMSDatabaseException;
import com.calix.ems.exception.EMSException;
import com.calix.ems.query.EMSGetAllQuery;
import com.calix.ems.query.ICMSQuery;
import com.calix.system.common.log.Log;
//END IMPORTS
import com.calix.ems.util.TLVHelper;
import com.calix.system.common.protocol.tlv.TLV;
import com.calix.system.server.dbmodel.*;

/**
 * Class B6ServicePackage.
 * 
 * @version $Revision$ $Date$
 */
public class B6ServicePackage extends com.calix.system.server.dbmodel.CMSObject {


      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field m_BinderIds
     */
    public String m_BinderIds;

    /**
     * Field m_DataService
     */
    public String m_DataService;

    /**
     * Field m_DataServiceProperties
     */
    public String m_DataServiceProperties;

    /**
     * Field m_Description
     */
    public String m_Description;

    /**
     * Field m_HasAutoGeneratedProfiles
     */
    public Integer m_HasAutoGeneratedProfiles;

    /**
     * Field m_IsMdu
     */
    public Integer m_IsMdu;

    /**
     * Field m_Name
     */
    public com.calix.system.server.dbmodel.ICMSAid m_Name;

    /**
     * Field m_PWE3Service
     */
    public String m_PWE3Service;

    /**
     * Field m_PackageType
     */
    public Integer m_PackageType;

    /**
     * Field m_RgService
     */
    public Integer m_RgService;

    /**
     * Field m_RgServiceProperties
     */
    public String m_RgServiceProperties;

    /**
     * Field m_ServicePackageProperties
     */
    public String m_ServicePackageProperties;

    /**
     * Field m_Status
     */
    public Integer m_Status;

    /**
     * Field m_TLSService
     */
    public String m_TLSService;

    /**
     * Field m_VideoService
     */
    public String m_VideoService;

    /**
     * Field m_VideoServiceProperties
     */
    public String m_VideoServiceProperties;

    /**
     * Field m_VoiceService
     */
    public String m_VoiceService;

    /**
     * Field m_VoiceServiceProperties
     */
    public String m_VoiceServiceProperties;

    /**
     * Field m_VoipService
     */
    public Integer m_VoipService;

    /**
     * Field m_VoipServiceProperties
     */
    public String m_VoipServiceProperties;

    /**
     * Field TYPE_NAME
     */
    public static String TYPE_NAME = "B6ServicePackage";

    /**
     * Field flowID
     */
    public static final int flowID = 1;


      //----------------/
     //- Constructors -/
    //----------------/

    public B6ServicePackage() {
        super();
    } //-- com.calix.bseries.server.dbmodel.B6ServicePackage()


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method copyFields
     * 
     * @param obj1
     */
    protected void copyFields(CMSObject obj1)
    {
        if( obj1 instanceof B6ServicePackage ) {
            super.copyFields(obj1);
            B6ServicePackage obj = (B6ServicePackage)obj1;
            setBinderIds((String)Helper.copy(obj.getBinderIds()));
            setDataService((String)Helper.copy(obj.getDataService()));
            setDataServiceProperties((String)Helper.copy(obj.getDataServiceProperties()));
            setDescription((String)Helper.copy(obj.getDescription()));
            setHasAutoGeneratedProfiles((Integer)Helper.copy(obj.getHasAutoGeneratedProfiles()));
            setIsMdu((Integer)Helper.copy(obj.getIsMdu()));
            setName((com.calix.system.server.dbmodel.ICMSAid)Helper.copy(obj.getName()));
            setPWE3Service((String)Helper.copy(obj.getPWE3Service()));
            setPackageType((Integer)Helper.copy(obj.getPackageType()));
            setRgService((Integer)Helper.copy(obj.getRgService()));
            setRgServiceProperties((String)Helper.copy(obj.getRgServiceProperties()));
            setServicePackageProperties((String)Helper.copy(obj.getServicePackageProperties()));
            setStatus((Integer)Helper.copy(obj.getStatus()));
            setTLSService((String)Helper.copy(obj.getTLSService()));
            setVideoService((String)Helper.copy(obj.getVideoService()));
            setVideoServiceProperties((String)Helper.copy(obj.getVideoServiceProperties()));
            setVoiceService((String)Helper.copy(obj.getVoiceService()));
            setVoiceServiceProperties((String)Helper.copy(obj.getVoiceServiceProperties()));
            setVoipService((Integer)Helper.copy(obj.getVoipService()));
            setVoipServiceProperties((String)Helper.copy(obj.getVoipServiceProperties()));
            setIdentityValue((com.calix.system.server.dbmodel.ICMSAid)Helper.copy(obj.getIdentityValue()));
        }
    } //-- void copyFields(CMSObject) 

    /**
     * Method getBinderIds
     */
    public String getBinderIds()
    {
        return this.m_BinderIds;
    } //-- String getBinderIds() 

    /**
     * Method getDataService
     */
    public String getDataService()
    {
        return this.m_DataService;
    } //-- String getDataService() 

    /**
     * Method getDataServiceProperties
     */
    public String getDataServiceProperties()
    {
        return this.m_DataServiceProperties;
    } //-- String getDataServiceProperties() 

    /**
     * Method getDescription
     */
    public String getDescription()
    {
        return this.m_Description;
    } //-- String getDescription() 

    /**
     * Method getHasAutoGeneratedProfiles
     */
    public Integer getHasAutoGeneratedProfiles()
    {
        return this.m_HasAutoGeneratedProfiles;
    } //-- Integer getHasAutoGeneratedProfiles() 

    /**
     * Method getIdentityValue
     */
    public com.calix.system.server.dbmodel.ICMSAid getIdentityValue()
    {
        return this.m_Name;
    } //-- com.calix.system.server.dbmodel.ICMSAid getIdentityValue() 

    /**
     * Method getIsMdu
     */
    public Integer getIsMdu()
    {
        return this.m_IsMdu;
    } //-- Integer getIsMdu() 

    /**
     * Method getName
     */
    public com.calix.system.server.dbmodel.ICMSAid getName()
    {
        return this.m_Name;
    } //-- com.calix.system.server.dbmodel.ICMSAid getName() 

    /**
     * Method getPWE3Service
     */
    public String getPWE3Service()
    {
        return this.m_PWE3Service;
    } //-- String getPWE3Service() 

    /**
     * Method getPackageType
     */
    public Integer getPackageType()
    {
        return this.m_PackageType;
    } //-- Integer getPackageType() 

    /**
     * Method getRgService
     */
    public Integer getRgService()
    {
        return this.m_RgService;
    } //-- Integer getRgService() 

    /**
     * Method getRgServiceProperties
     */
    public String getRgServiceProperties()
    {
        return this.m_RgServiceProperties;
    } //-- String getRgServiceProperties() 

    /**
     * Method getServicePackageProperties
     */
    public String getServicePackageProperties()
    {
        return this.m_ServicePackageProperties;
    } //-- String getServicePackageProperties() 

    /**
     * Method getStatus
     */
    public Integer getStatus()
    {
        return this.m_Status;
    } //-- Integer getStatus() 

    /**
     * Method getTLSService
     */
    public String getTLSService()
    {
        return this.m_TLSService;
    } //-- String getTLSService() 

    /**
     * Method getTlvType
     */
    public int getTlvType()
    {
        return BseriesTlvConstants.B6ServicePackage;
    } //-- int getTlvType() 

    /**
     * Method getTypeName
     */
    public String getTypeName()
    {
        return TYPE_NAME;
    } //-- String getTypeName() 

    /**
     * Method getVideoService
     */
    public String getVideoService()
    {
        return this.m_VideoService;
    } //-- String getVideoService() 

    /**
     * Method getVideoServiceProperties
     */
    public String getVideoServiceProperties()
    {
        return this.m_VideoServiceProperties;
    } //-- String getVideoServiceProperties() 

    /**
     * Method getVoiceService
     */
    public String getVoiceService()
    {
        return this.m_VoiceService;
    } //-- String getVoiceService() 

    /**
     * Method getVoiceServiceProperties
     */
    public String getVoiceServiceProperties()
    {
        return this.m_VoiceServiceProperties;
    } //-- String getVoiceServiceProperties() 

    /**
     * Method getVoipService
     */
    public Integer getVoipService()
    {
        return this.m_VoipService;
    } //-- Integer getVoipService() 

    /**
     * Method getVoipServiceProperties
     */
    public String getVoipServiceProperties()
    {
        return this.m_VoipServiceProperties;
    } //-- String getVoipServiceProperties() 

    /**
     * Method populateAttributeFromTLV
     * 
     * @param tlv
     * @param from_version
     */
    public void populateAttributeFromTLV(TLV tlv, SwVersionNo from_version)
    {
        if (tlv == null)
            return;
        switch (tlv.getType()) {
            case 0x344D:
                if (m_PackageType == null) {
                    m_PackageType = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x344E:
                if (m_HasAutoGeneratedProfiles == null) {
                    m_HasAutoGeneratedProfiles = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x344F:
                if (m_Description == null) {
                    m_Description = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3450:
                if (m_DataService == null) {
                    m_DataService = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3451:
                if (m_DataServiceProperties == null) {
                    m_DataServiceProperties = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3452:
                if (m_VideoService == null) {
                    m_VideoService = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3453:
                if (m_VideoServiceProperties == null) {
                    m_VideoServiceProperties = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3454:
                if (m_VoiceService == null) {
                    m_VoiceService = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3455:
                if (m_VoiceServiceProperties == null) {
                    m_VoiceServiceProperties = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3456:
                if (m_VoipService == null) {
                    m_VoipService = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3457:
                if (m_VoipServiceProperties == null) {
                    m_VoipServiceProperties = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3458:
                if (m_RgService == null) {
                    m_RgService = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x3459:
                if (m_RgServiceProperties == null) {
                    m_RgServiceProperties = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x345A:
                if (m_PWE3Service == null) {
                    m_PWE3Service = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x345B:
                if (m_Status == null) {
                    m_Status = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x345C:
                if (m_IsMdu == null) {
                    m_IsMdu = TLVHelper.getIntegerValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x345D:
                if (m_TLSService == null) {
                    m_TLSService = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x345E:
                if (m_BinderIds == null) {
                    m_BinderIds = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
            case 0x345F:
                if (m_ServicePackageProperties == null) {
                    m_ServicePackageProperties = TLVHelper.getStringValueOfTLV(tlv );
                    return;
                }
                break;
        }
        super.populateAttributeFromTLV(tlv, from_version);
    } //-- void populateAttributeFromTLV(TLV, SwVersionNo) 

    /**
     * Method populateTLVFromAttributes
     * 
     * @param tlv
     * @param to_version
     */
    public void populateTLVFromAttributes(TLV tlv, SwVersionNo to_version)
    {
        if (tlv == null)
            return;
        super.populateTLVFromAttributes(tlv, to_version);
        TLVHelper.addEmbeddedTLV(tlv, 0x345E, m_BinderIds);
        TLVHelper.addEmbeddedTLV(tlv, 0x3450, m_DataService);
        TLVHelper.addEmbeddedTLV(tlv, 0x3451, m_DataServiceProperties);
        TLVHelper.addEmbeddedTLV(tlv, 0x344F, m_Description);
        TLVHelper.addEmbeddedTLV(tlv, 0x344E, m_HasAutoGeneratedProfiles);
        TLVHelper.addEmbeddedTLV(tlv, 0x345C, m_IsMdu);
        TLVHelper.addEmbeddedTLV(tlv, 0x345A, m_PWE3Service);
        TLVHelper.addEmbeddedTLV(tlv, 0x344D, m_PackageType);
        TLVHelper.addEmbeddedTLV(tlv, 0x3458, m_RgService);
        TLVHelper.addEmbeddedTLV(tlv, 0x3459, m_RgServiceProperties);
        TLVHelper.addEmbeddedTLV(tlv, 0x345F, m_ServicePackageProperties);
        TLVHelper.addEmbeddedTLV(tlv, 0x345B, m_Status);
        TLVHelper.addEmbeddedTLV(tlv, 0x345D, m_TLSService);
        TLVHelper.addEmbeddedTLV(tlv, 0x3452, m_VideoService);
        TLVHelper.addEmbeddedTLV(tlv, 0x3453, m_VideoServiceProperties);
        TLVHelper.addEmbeddedTLV(tlv, 0x3454, m_VoiceService);
        TLVHelper.addEmbeddedTLV(tlv, 0x3455, m_VoiceServiceProperties);
        TLVHelper.addEmbeddedTLV(tlv, 0x3456, m_VoipService);
        TLVHelper.addEmbeddedTLV(tlv, 0x3457, m_VoipServiceProperties);
    } //-- void populateTLVFromAttributes(TLV, SwVersionNo) 

    /**
     * Method setBinderIds
     * 
     * @param BinderIds
     */
    public void setBinderIds(String BinderIds)
    {
        this.m_BinderIds = BinderIds;
    } //-- void setBinderIds(String) 

    /**
     * Method setDataService
     * 
     * @param DataService
     */
    public void setDataService(String DataService)
    {
        this.m_DataService = DataService;
    } //-- void setDataService(String) 

    /**
     * Method setDataServiceProperties
     * 
     * @param DataServiceProperties
     */
    public void setDataServiceProperties(String DataServiceProperties)
    {
        this.m_DataServiceProperties = DataServiceProperties;
    } //-- void setDataServiceProperties(String) 

    /**
     * Method setDescription
     * 
     * @param Description
     */
    public void setDescription(String Description)
    {
        this.m_Description = Description;
    } //-- void setDescription(String) 

    /**
     * Method setHasAutoGeneratedProfiles
     * 
     * @param HasAutoGeneratedProfiles
     */
    public void setHasAutoGeneratedProfiles(Integer HasAutoGeneratedProfiles)
    {
        this.m_HasAutoGeneratedProfiles = HasAutoGeneratedProfiles;
    } //-- void setHasAutoGeneratedProfiles(Integer) 

    /**
     * Method setIdentityValue
     * 
     * @param Name
     */
    public boolean setIdentityValue(com.calix.system.server.dbmodel.ICMSAid Name)
    {
        this.m_Name = (com.calix.system.server.dbmodel.ICMSAid)Name;
        return true;
    } //-- boolean setIdentityValue(com.calix.system.server.dbmodel.ICMSAid) 

    /**
     * Method setIsMdu
     * 
     * @param IsMdu
     */
    public void setIsMdu(Integer IsMdu)
    {
        this.m_IsMdu = IsMdu;
    } //-- void setIsMdu(Integer) 

    /**
     * Method setName
     * 
     * @param Name
     */
    public void setName(com.calix.system.server.dbmodel.ICMSAid Name)
    {
        this.m_Name = Name;
    } //-- void setName(com.calix.system.server.dbmodel.ICMSAid) 

    /**
     * Method setPWE3Service
     * 
     * @param PWE3Service
     */
    public void setPWE3Service(String PWE3Service)
    {
        this.m_PWE3Service = PWE3Service;
    } //-- void setPWE3Service(String) 

    /**
     * Method setPackageType
     * 
     * @param PackageType
     */
    public void setPackageType(Integer PackageType)
    {
        this.m_PackageType = PackageType;
    } //-- void setPackageType(Integer) 

    /**
     * Method setRgService
     * 
     * @param RgService
     */
    public void setRgService(Integer RgService)
    {
        this.m_RgService = RgService;
    } //-- void setRgService(Integer) 

    /**
     * Method setRgServiceProperties
     * 
     * @param RgServiceProperties
     */
    public void setRgServiceProperties(String RgServiceProperties)
    {
        this.m_RgServiceProperties = RgServiceProperties;
    } //-- void setRgServiceProperties(String) 

    /**
     * Method setServicePackageProperties
     * 
     * @param ServicePackageProperties
     */
    public void setServicePackageProperties(String ServicePackageProperties)
    {
        this.m_ServicePackageProperties = ServicePackageProperties;
    } //-- void setServicePackageProperties(String) 

    /**
     * Method setStatus
     * 
     * @param Status
     */
    public void setStatus(Integer Status)
    {
        this.m_Status = Status;
    } //-- void setStatus(Integer) 

    /**
     * Method setTLSService
     * 
     * @param TLSService
     */
    public void setTLSService(String TLSService)
    {
        this.m_TLSService = TLSService;
    } //-- void setTLSService(String) 

    /**
     * Method setTypeName
     * 
     * @param typeName
     */
    public boolean setTypeName(String typeName)
    {
        return false;
    } //-- boolean setTypeName(String) 

    /**
     * Method setVideoService
     * 
     * @param VideoService
     */
    public void setVideoService(String VideoService)
    {
        this.m_VideoService = VideoService;
    } //-- void setVideoService(String) 

    /**
     * Method setVideoServiceProperties
     * 
     * @param VideoServiceProperties
     */
    public void setVideoServiceProperties(String VideoServiceProperties)
    {
        this.m_VideoServiceProperties = VideoServiceProperties;
    } //-- void setVideoServiceProperties(String) 

    /**
     * Method setVoiceService
     * 
     * @param VoiceService
     */
    public void setVoiceService(String VoiceService)
    {
        this.m_VoiceService = VoiceService;
    } //-- void setVoiceService(String) 

    /**
     * Method setVoiceServiceProperties
     * 
     * @param VoiceServiceProperties
     */
    public void setVoiceServiceProperties(String VoiceServiceProperties)
    {
        this.m_VoiceServiceProperties = VoiceServiceProperties;
    } //-- void setVoiceServiceProperties(String) 

    /**
     * Method setVoipService
     * 
     * @param VoipService
     */
    public void setVoipService(Integer VoipService)
    {
        this.m_VoipService = VoipService;
    } //-- void setVoipService(Integer) 

    /**
     * Method setVoipServiceProperties
     * 
     * @param VoipServiceProperties
     */
    public void setVoipServiceProperties(String VoipServiceProperties)
    {
        this.m_VoipServiceProperties = VoipServiceProperties;
    } //-- void setVoipServiceProperties(String) 

    /**
     * Method updateFields
     * 
     * @param obj1
     */
    protected void updateFields(CMSObject obj1)
    {
        if( obj1 instanceof B6ServicePackage ) {
            super.updateFields(obj1);
            B6ServicePackage obj = (B6ServicePackage)obj1;
           if (obj.getBinderIds() != null )
               setBinderIds((String)Helper.copy(obj.getBinderIds()));
           if (obj.getDataService() != null )
               setDataService((String)Helper.copy(obj.getDataService()));
           if (obj.getDataServiceProperties() != null )
               setDataServiceProperties((String)Helper.copy(obj.getDataServiceProperties()));
           if (obj.getDescription() != null )
               setDescription((String)Helper.copy(obj.getDescription()));
           if (obj.getHasAutoGeneratedProfiles() != null )
               setHasAutoGeneratedProfiles((Integer)Helper.copy(obj.getHasAutoGeneratedProfiles()));
           if (obj.getIsMdu() != null )
               setIsMdu((Integer)Helper.copy(obj.getIsMdu()));
           if (obj.getName() != null )
               setName((com.calix.system.server.dbmodel.ICMSAid)Helper.copy(obj.getName()));
           if (obj.getPWE3Service() != null )
               setPWE3Service((String)Helper.copy(obj.getPWE3Service()));
           if (obj.getPackageType() != null )
               setPackageType((Integer)Helper.copy(obj.getPackageType()));
           if (obj.getRgService() != null )
               setRgService((Integer)Helper.copy(obj.getRgService()));
           if (obj.getRgServiceProperties() != null )
               setRgServiceProperties((String)Helper.copy(obj.getRgServiceProperties()));
           if (obj.getServicePackageProperties() != null )
               setServicePackageProperties((String)Helper.copy(obj.getServicePackageProperties()));
           if (obj.getStatus() != null )
               setStatus((Integer)Helper.copy(obj.getStatus()));
           if (obj.getTLSService() != null )
               setTLSService((String)Helper.copy(obj.getTLSService()));
           if (obj.getVideoService() != null )
               setVideoService((String)Helper.copy(obj.getVideoService()));
           if (obj.getVideoServiceProperties() != null )
               setVideoServiceProperties((String)Helper.copy(obj.getVideoServiceProperties()));
           if (obj.getVoiceService() != null )
               setVoiceService((String)Helper.copy(obj.getVoiceService()));
           if (obj.getVoiceServiceProperties() != null )
               setVoiceServiceProperties((String)Helper.copy(obj.getVoiceServiceProperties()));
           if (obj.getVoipService() != null )
               setVoipService((Integer)Helper.copy(obj.getVoipService()));
           if (obj.getVoipServiceProperties() != null )
               setVoipServiceProperties((String)Helper.copy(obj.getVoipServiceProperties()));
           if (obj.getIdentityValue() != null )
               setIdentityValue((com.calix.system.server.dbmodel.ICMSAid)Helper.copy(obj.getIdentityValue()));
        }
    } //-- void updateFields(CMSObject) 
//	BEGIN CODE
    
    public void setconvertIsMdu(Boolean isMdu){
    	if(isMdu != null){
    		if(isMdu == true)
        		this.m_IsMdu = 1;
        	else
        		this.m_IsMdu = 0;
    	}
    	else
    		this.m_IsMdu = null;
    	
    }
    
    public Boolean getconvertIsMdu(){
    	if(this.m_IsMdu != null)
    	{
    		if(this.m_IsMdu == 0)
    			return false;
    		else 
    			return true;
    	}
    	else
    		return null;
    }
	public void setconvertName(String convertName) {
		this.m_Name = new EMSAid(convertName);
	} // -- void setconvertName(String)

	public String getconvertName() {
		return this.m_Name.toString();
	} // -- String getconvertName()
    
	public Collection doQuery(DbTransaction tx, String filter)
			throws EMSException {
		if (Log.db().isDebugEnabled())
			Log.db().debug("Inside doQuery");
		ICMSQuery query = getDBQuery(this.getTypeName(), null);
		Collection coll = query.exec((Object) tx.getDatabase(), (Object) tx);
		if (Log.db().isDebugEnabled())
			Log.db().debug("Out of doQuery");
		return coll;
	}

	public CMSObject doLoad(DbTransaction tx) throws EMSException {
		C7Database db = C7Database.getInstance();
		CMSObject obj = null;
		try {
			db.beginTransaction();
			Collection resultList = db.executeQuery(this.getClass(), "name = '"
					+ this.getIdentityValue().toString() + "'", -1, -1);
			if (resultList != null && !resultList.isEmpty()) {
				Iterator itr = resultList.iterator();
				obj = (CMSObject) itr.next();
			}
			db.commitTransaction();
			} catch (Exception e) {
				e.printStackTrace();
				db.rollbackTransaction();
			}finally{
				db.close();
			}
		if (obj == null)
			throw new EMSDatabaseException(
					EMSDatabaseException._loadNonExistentFail_,
					"Object does not exist");
		else
			return obj;
	}

	public ICMSQuery getDBQuery(String type, String filter) {
		if (filter == null || filter.equals(""))
			return new EMSGetAllQuery(type);
		else {
			Log.meta().error("BaseEMSObject: filterQuery is not supported");
			return null;
		}
	}

	public boolean isIdentityValuePrimaryKey() {
		return true;
	}
//  END CODE
}
